### ISSUE TITLE
Some question about this when run the code

### ISSUE THREAD

**Issue by jucaizhai** [Emanual20/Yulan-GARDEN#2]
Hello, your work is so good! I'm a newcomer in this field. While I follow your guide to run the code like this , I download the mini openwebtext2 for input. when I run the code,  the output file is empty. I don't know how to solve it.
![image](https://github.com/Emanual20/Yulan-GARDEN/assets/94056015/471a3f7f-34c4-4705-96a3-1d36e414c153)

**Comment by jucaizhai** [comment]
Also, How to deal with the input dataset file like openwebtext2? you say you provide the method for data processing recipes, but I can't find it.

**Comment by Emanual20** [comment]
Dear qyleni,

Thanks for your attention to our work.

In terms of your first question, as no further details about the errors of running Yulan-GARDEN are provided, I suppose the mini openwebtext2 you downloaded is not in the format of JSONL. To specify the {{input_ext}} in config file, you are supposed to serve each data point in one line, while a json dict containing {{input_text_key}} field in one line.

As for your second question, we provide our data processing recipe for openwebtext2 to reproduce the experiment result reported in our paper can be found in [here](https://github.com/Emanual20/Yulan-GARDEN/blob/main/settings/openwebtext2.json). 

I wish this response could help your figure out your issues.

Emanual20, Yulan-GARDEN Team

**Comment by Emanual20** [comment]
As no further comments are addressed, this issue will be closed. Please feel free to reopen it if you have any other questions. We are looking forward to your feedback.
