### ISSUE TITLE
执行命令 python main.py --conf settings/example.json，出现报错 FileNotFoundError: [Errno 2] No such file or directory: '/root/autodl-tmp/Yulan-GARDEN/tmp/process.log'

### ISSUE THREAD

**Issue by Daniel-bupt** [Emanual20/Yulan-GARDEN#3]
Yulan-GARDEN目录下没有相应的内容？请问怎么处理？

**Comment by Daniel-bupt** [comment]
![image](https://github.com/RUC-GSAI/Yulan-GARDEN/assets/52708115/c95ca010-1ec7-4c01-9206-174b6d139555)

**Comment by PhealenWang** [comment]
已修复这个bug，pull最新的代码就可以～

**Comment by Emanual20** [comment]
As no further comments are addressed, this issue will be closed. Please feel free to reopen it if you have any other questions. We are looking forward to your feedback.
