### ISSUE TITLE
你好，目前遇到一个问题，按照quick start操作，保证output_path不存在，却报了如下的错误，请问该怎么解决？谢谢

### ISSUE THREAD

**Issue by Daniel-bupt** [Emanual20/Yulan-GARDEN#4]
![image](https://github.com/RUC-GSAI/Yulan-GARDEN/assets/52708115/ec3ba569-abf3-469e-afe0-6f990c0ce221)

**Comment by PhealenWang** [comment]
你好，配置文件中的路径（包括input_path, output_path等）都为绝对路径，请不要使用相对路径，请您使用绝对路径再次运行代码。

**Comment by Daniel-bupt** [comment]
> 你好，配置文件中的路径（包括input_path, output_path等）都为绝对路径，请不要使用相对路径，请您使用绝对路径再次运行代码。

完美解决问题，可以正常运行了，万分感谢

**Comment by Emanual20** [comment]
As no further comments are addressed, this issue will be closed. Please feel free to reopen it if you have any other questions. We are looking forward to your feedback.
