### ISSUE TITLE
About Kenlm

### ISSUE THREAD

**Issue by Mrkkew** [Emanual20/Yulan-GARDEN#6]
在运行时候，好像是kenlm部分的引入报错了，这个模型需要自己下载吗？可以怎么解决呢？
![image](https://github.com/user-attachments/assets/791f6e88-94ba-40d5-9d7a-27fbf81e0292)

**Comment by Mrkkew** [comment]
解决了，模型没有下载完

**Comment by PhealenWang** [comment]
已在utils/models/kenlm中的readme进行了进一步补充说明，写明了具体要下载哪些文件。
