### ISSUE TITLE
对参数的疑问

### ISSUE THREAD

**Issue by Mrkkew** [Emanual20/Yulan-GARDEN#7]
整个项目的参数太多，能不能出一个对参数设置的说明啊，各种报错，不知道怎么对数据进行处理的

**Comment by Mrkkew** [comment]
输入文件的格式最好也有个说明

**Comment by PhealenWang** [comment]
在项目的readme中增加了settings的简要描述，各个部分的详细信息在utils/workers的readme以及各个模块的readme中。
